### ISSUE TITLE
Auto-complete during 'Edit BOM'

### ISSUE THREAD

**Issue by patrick-tyger1** [mpkasp/indabom#14]
To help with usability, an auto search or auto complete for adding new items to a BOM would make it much faster and easier to create BOM structures. Without this, one needs to already know all of their part numbers beforehand which means they basically already need a bom in front of them

**Comment by mpkasp** [comment]
@patrick-tyger1 I agree. I had this implemented at one point, will need to look into what happened. Probably some regression here...

**Comment by mpkasp** [comment]
Oops I spoke too soon - a few things: this is implemented on the home dashboard search, not on "edit bom". Secondly I need to move this ticket to the [django-bom repository](https://github.com/mpkasp/django-bom/). 

I created the issue [here](https://github.com/mpkasp/django-bom/issues/44).

Please subscribe to that issue if you would like updates. I'll be closing this one.
