### ISSUE TITLE
Implement other part finder services

### ISSUE THREAD

**Issue by nbourre** [mpkasp/indabom#2]
We are using PartChips at my place.

How hard would it be to implement other part finder services?

**Comment by mpkasp** [comment]
I'm not familiar with PartChips. A quick Google comes up with FindChips, is that what you mean? https://www.findchips.com/

**Comment by nbourre** [comment]
Yes, it is the good website. Actually, we've developed an excel file with a VBA script.

**Comment by mpkasp** [comment]
Closing this one as it's been inactive, and should be moved to the django-bom repository now.
