### ISSUE TITLE
Useability - manage ellipsis is often off the right of the window and required scrolling

### ISSUE THREAD

**Issue by danielgcom** [mpkasp/indabom#33]
When managing the BOM for an individual part (e.g at https://indabom.com/bom/part/17834/rev/18871/manage-bom/ ), the ellipsis is the last column... making it a pain to scroll over to find.

![image](https://user-images.githubusercontent.com/78202234/142904099-bdd4ccaa-dc1d-4e78-89bb-401341159272.png)

One solution might be to make the 'level' field clickable at the point, and to provide the same "edit or change / remove" drop-down menu from it.

**Comment by mpkasp** [comment]
Moved to django-bom repository.
