### ISSUE TITLE
Part number syntax

### ISSUE THREAD

**Issue by ziogianni** [mpkasp/indabom#4]
Hello everyone, I'm looking for a way to modify the part number syntax in order to better customize this platform to my needs. Take into account that every business has its own way to code parts, so I suppose that it'd be useful to provide a config file where you can decide your own part number syntax, going beyond the predefined structure which mainly fits to the electronics scope.

**Comment by mpkasp** [comment]
Firstly this issue should be on the [django-bom](https://github.com/mpkasp/django-bom) repository - I will close it here as I have moved it over for you [here](https://github.com/mpkasp/django-bom/issues/17).

I've been thinking about modifying this so the user can set whatever they want. One of the features we get from the number format I have now is that it can auto-increment. That being said I think there's still a way we can achieve this with a custom format.

To make the long story short - you currently can't change the number syntax unless you're comfortable jumping into code. If you are comfortable check out the models.py file PartClass and Part data models.

**Comment by ziogianni** [comment]
Ok got it, let's think about a future enhancement. I let you know if i'll
be able to fiddle with django source code.

Regards

Il Dom 20 Ott 2019, 18:16 Mike Kasparian <notifications@github.com> ha
scritto:
